#pragma kernel BoundFlow
#pragma kernel EdgeFlow_X
#pragma kernel EdgeFlow_Y
#pragma kernel EdgeFlow_Z

#pragma enable_d3d11_debug_symbols

StructuredBuffer<int> prop; 
RWStructuredBuffer<int> data;
RWStructuredBuffer<int> next;
RWStructuredBuffer<int> resu;

/*int strideZ, strideY, strideX;

[numthreads(1,1,1)]
void Init (uint3 id : SV_DispatchThreadID)
{
    strideZ = 1;                          
    strideY = prop[5] * strideZ;            
    strideX = prop[4] * strideY;     
}*/

[numthreads(8,8,16)]
void BoundFlow (uint3 id : SV_DispatchThreadID)
{
    int x = id.x + 1;
    int y = id.y + 1;
    int z = id.z + 1;
       
    int index = x * prop[8] + y * prop[7] + z;

    int center = data[index];
    int val = center - (center / 7) * 6;
    //InterlockedAdd(resu[0],prop[0]);
    //InterlockedAdd(resu[1],prop[1]);
    //InterlockedAdd(resu[2],prop[2]);
    //InterlockedAdd(resu[3],val);
    //resu[0] = strideZ;

    val += data[index + prop[8]] / 7;    // x+1
    val += data[index - prop[8]] / 7;    // x-1
    val += data[index + prop[7]] / 7;    // y+1
    val += data[index - prop[7]] / 7;    // y-1
    val += data[index + 1] / 7;    // z+1
    val += data[index - 1] / 7;    // z-1

    next[index] = val;
}

[numthreads(8,8,1)]
void EdgeFlow_X (uint2 id : SV_DispatchThreadID)
{
    int y = id.x + 1;
    int z = id.y + 1;

    int index_x0 = y * prop[7] + z;
    next[index_x0 + prop[8]] += data[index_x0] / 7;

    int index_xMax = (prop[0]+1) * prop[8] + y * prop[7] + z;
    next[index_xMax - prop[8]] += data[index_xMax] / 7;
}

[numthreads(8,8,1)]
void EdgeFlow_Y (uint2 id : SV_DispatchThreadID)
{
    int x = id.x + 1;
    int z = id.y + 1;

    int index_y0 = x * prop[8] + z;
    next[index_y0 + prop[7]] += data[index_y0] / 7;

    int index_yMax = x * prop[8] + (prop[1]+1) * prop[7] + z;
    next[index_yMax - prop[7]] += data[index_yMax] / 7;
}

[numthreads(8,8,1)]
void EdgeFlow_Z (uint2 id : SV_DispatchThreadID)
{
    int x = id.x + 1;
    int y = id.y + 1;

    int index_z0 = x * prop[8] + y * prop[7];
    next[index_z0 + 1] += data[index_z0] / 7;

    int index_zMax = x * prop[8] + y * prop[7] + prop[2] + 1;
    next[index_zMax - 1] += data[index_zMax] / 7;
}